name: zero-degree-infra

plugins:
  - name: vyper
  - name: avalanche

default_ecosystem: avalanche

vyper:
  version: 0.4.0
  enable_decimals: true
  evm_version: shanghai

networks:
  avalanche:
    fuji:
      default_provider: node

node:
  avalanche:
    fuji:
      uri: https://api.avax-test.network/ext/bc/C/rpc

alchemy:
  avalanche:
    fuji:
      uri: https://avax-fuji.g.alchemy.com/v2/${WEB3_ALCHEMY_API_KEY}

etherscan:
  avalanche:
    fuji:
      uri: https://api.routescan.io/v2/network/testnet/evm/43113/etherscan/api